services:
  studyabroaddocker-app:
    image: 'studyabroaddocker:latest'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/studyabroaddocker
    container_name: studyabroad
    depends_on:
      - studyabroaddb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://studyabroaddb:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
          
  studyabroaddb:
    image: 'postgres:latest'
    container_name: studyabroaddb
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'